OUTPUT:
b'\r\nC:\\GitHub\\CWatM\\Tutorials\\09_Calibration_renovation\\runs_calibration\\00_001>python ../../../../run_cwatm.py settings_CWatM_template_30min-Run00_001.ini -v \r\n'
ERRORS:
b'Traceback (most recent call last):\r\n  File "C:\\GitHub\\CWatM\\run_cwatm.py", line 35, in <module>\r\n    from cwatm.run_cwatm import main, parse_args, usage, GNU\r\n  File "C:\\GitHub\\CWatM\\cwatm\\run_cwatm.py", line 38, in <module>\r\n    import numpy as np\r\n  File "C:\\Users\\smilovic\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\__init__.py", line 153, in <module>\r\n    from . import ma\r\n  File "C:\\Users\\smilovic\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\ma\\__init__.py", line 42, in <module>\r\n    from . import core\r\n  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load\r\n  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked\r\n  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked\r\n  File "<frozen importlib._bootstrap_external>", line 936, in exec_module\r\n  File "<frozen importlib._bootstrap_external>", line 1032, in get_code\r\n  File "<frozen importlib._bootstrap_external>", line 1131, in get_data\r\nMemoryError\r\n'